server:
 port: 8082
spring :
  profiles:
    active: dev
  application:
    name: USER-SERVICE
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Passw0rd
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  profiles: qa
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Passw0rd
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/javafsd
    username: root
    password: Passw0rd
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:8761/eureka/
 instance:
  hostname: localhost
